# Generated by Django 4.2.7 on 2023-11-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subscription', verbose_name='subscription'),
        ),
    ]
