# Generated by Django 4.2.7 on 2023-11-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
