# Generated by Django 4.2.7 on 2023-11-01 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Transfer', 'Transfer')], default='Card', max_length=255, verbose_name='Payment Method')),
                ('course_payment', models.SmallIntegerField(blank=True, choices=[('Courses', [])], null=True, verbose_name='Course Payment')),
                ('lesson_payment', models.SmallIntegerField(blank=True, choices=[('Lessons', [])], null=True, verbose_name='Lesson Payment')),
                ('payment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Payment Owner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
