# Generated by Django 4.2.7 on 2023-11-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course_payment',
            field=models.SmallIntegerField(blank=True, choices=[('Courses', [(1, 'Python For Beginners')])], null=True, verbose_name='Course Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson_payment',
            field=models.SmallIntegerField(blank=True, choices=[('Lessons', [(1, 'Python Intro N1!'), (2, 'Python Intro N2')])], null=True, verbose_name='Lesson Payment'),
        ),
    ]
