# Generated by Django 4.2.7 on 2023-11-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_subscription'),
        ('payment', '0002_alter_payment_course_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lesson_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='course.course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='course.lesson'),
        ),
    ]
