# Generated by Django 4.2.7 on 2023-11-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_course_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course',
            new_name='course_payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='lesson',
            new_name='lesson_payment',
        ),
    ]
